# Generated by Django 5.0.3 on 2024-03-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="inventory",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="title",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="bookingDate",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="no_of_guests",
            field=models.IntegerField(null=True),
        ),
    ]
